version: '3.2'

services:
  app-localcosmos:
    image: poc:latest
    restart: "no"
    container_name: "app-localcosmos"
    env_file:
      - .\app.localcosmos.env
  app-cosmos:
    image: poc:latest
    restart: "no"
    container_name: "app-cosmos"
    env_file:
      - .\app.cosmos.env
  app-mongo:
    image: poc:latest
    restart: "no"
    container_name: "app-mongo"
    env_file:
      - .\app.mongo.env
    links:
      - mongo
    ports:
      - "8080:3000"
  mongo:
    image: mongo:3.6
    command: [--auth]
    restart: "always"
    container_name: "mongo"
    env_file:
      - .\mongo.env
    ports:
      - "27017:27017"
      - "9229:9229"
